name: Retrieve Salesforce Package

on:
  push:
    branches:
      - main

jobs:
  retrieve:
    name: Retrieve Metadata from Dev Org
    runs-on: self-hosted  # Uses your self-hosted runner (deployment agent from "project X")

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Salesforce CLI Path
        run: |
          echo "Adding Salesforce CLI to PATH..."
          echo "PATH=\"C:\\Program Files\\Salesforce CLI\\bin\\\":$PATH" >> $GITHUB_ENV
          sf --version

      - name: Authenticate to Dev Org (Web Login)
        run: |
          echo "Authenticating to Dev Org..."
          sf auth:web:login --setalias dev --instanceurl https://taruavocette4-dev-ed.develop.my.salesforce.com

      - name: Retrieve Metadata from Dev Org
        run: |
          echo "Retrieving metadata from package.xml..."
          sf project retrieve start --manifest manifest/package.xml
