name: Retrieve Metadata

on:
  push:
    branches:
      - main

jobs:
  retrieve:
    name: Retrieve Metadata from Dev Org
    runs-on: self-hosted  # This will use your local deployment pool agent

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Salesforce CLI Path
        run: |
          echo "Adding Salesforce CLI to PATH..."
          echo "PATH='C:\\Program Files\\Salesforce CLI\\bin\\':$PATH" >> $GITHUB_ENV
          sf --version

      - name: Authenticate to Dev Org
        run: |
          sf auth:web:login --setalias dev --instanceurl https://taruavocette4-dev-ed.develop.my.salesforce.com

      - name: Retrieve Metadata (package.xml)
        run: |
          sf project retrieve start --manifest manifest/package.xml
