trigger:
  branches:
    include:
      - main

pool:
  name: 'project X'  # Your offline/self-hosted deployment pool

steps:
  - checkout: self

  - script: |
      echo "Adding Salesforce CLI to PATH..."
      set PATH="C:\Program Files\Salesforce CLI\bin";%PATH%
      sf --version
    displayName: 'Set Salesforce CLI Path'

  - script: |
      echo "Authenticating to Dev Org..."
      sf auth:web:login --setalias dev --instance-url https://taruavocette4-dev-ed.develop.lightning.force.com
    displayName: 'Authenticate to Dev Org'

  - script: |
      echo "Retrieving metadata using package.xml..."
      sf project retrieve start --manifest manifest/package.xml
    displayName: 'Retrieve Metadata'
