trigger:
  branches:
    include:
      - main

jobs:
  - job: retrieve
    displayName: 'Retrieve Salesforce Metadata Package'
    deployment:
      pool:
        name: 'project X'  # Your deployment pool name

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
              displayName: 'Checkout repository'

            - script: |
                echo "Adding Salesforce CLI to PATH..."
                echo "##vso[task.setvariable variable=PATH]\"C:\Program Files\Salesforce CLI\bin\";$(PATH)"
                echo "Updated PATH: $(PATH)"
                sf --version
              displayName: 'Set Salesforce CLI Path'

            - script: |
                echo "Authenticating to Dev Org using web login..."
                sf auth:web:login --setalias dev --instanceurl https://taruavocette4-dev-ed.develop.my.salesforce.com
              displayName: 'Authenticate to Dev Org'

            - script: |
                echo "Retrieving metadata using package.xml manifest..."
                sf project retrieve start --manifest manifest/package.xml
              displayName: 'Retrieve metadata from Dev Org'
